## 1. Write a program to calculate Addition or Subtraction of 2 Matrices.


In [21]:
import numpy as np
a= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

b= np.array([
    [11,12,13],
    [14,12,19],
    [2,9,8]
])

print( a+b)

print(a-b)   # remember a-b != b-a

print (b-a)

[[12 14 16]
 [18 17 25]
 [ 9 17 17]]
[[-10 -10 -10]
 [-10  -7 -13]
 [  5  -1   1]]
[[10 10 10]
 [10  7 13]
 [-5  1 -1]]


## 2. Write a program to check if a given Matrix is an Identity Matrix (Diagonal 1 Rest 0).


In [25]:
import numpy as np
m = np.array([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,5,0],
    [0,0,0,1]
])
row= len(m)
col = len(m[0])
iden = True
if row!=col or row==0:
    iden= False
else:
    for i in range(row):
        for j in range(col):
            if (i == j) and (m[i][j] != 1):
                iden = False
                break
            elif (i!= j) and (m[i][j] != 0):
                iden = False
                break    
            
print("It is a identity matrix : ",iden)               
        

It is a identity matrix :  False


## 3. Write a program to sort Rows of Matrix in Ascending Order & Columns in Descendng Order.


In [28]:
import numpy as np
a = np.array([
    [3, 1, 4],
    [1, 5, 9],
    [2, 6, 8]
])

rows, cols = a.shape
sort_rows = np.sort(a, axis=1)

trans = sort_rows.T

col_t = np.sort(trans, axis=1)[:, ::-1]
final = col_t.T

print(final)

[[2 6 9]
 [1 5 8]
 [1 3 4]]


## 4. Write a program to accept Matrix & Interchange the Diagonals.


In [96]:
m= [[41,2,3],
    [4,18,6],
    [7,8,99]]
d= m
row = len(m)
col = len(m[0])
for i in range(row):
    for j in range(col):
        if i == j:
           m[i][i],m[i][row-i-1] = d[i][row-i-1], d[i][i]

print(d)

[[3, 2, 41], [4, 18, 6], [99, 8, 7]]


## 5. Write a program to calculate Sum of Main & Opposite Diagonal Elements of a Matrix.


In [55]:
m= [[1,2,3],
    [4,5,6],
    [9,8,9]]

row = len(m)
col = len(m[0])
d= []
od= []
for i in range(row):
    for j in range(col):
        if i == j:
           d.append(m[i][j])
for i in range(row):
    od.append(m[i][row-i-1])


print("The Sum of elements of main Diagonal is :", sum(d))
print("The Sum of elements of Opposite Diagonal is :", sum(od))

The Sum of elements of main Diagonal is : 15
The Sum of elements of Opposite Diagonal is : 17


## 6. Write a program to calculate Trace (Sum Of Diagonal) & Normal (Square Root Of Sum Of Square Of All Elements) of a given Matrix.

In [47]:

m= [[1,2,3],
    [4,5,6],
    [7,8,9]]
d =[]
sq = []
row = len(m)
col = len(m[0])

for i in range(row):
    for j in range(col):
        sq.append((m[i][j])**2)
        if i == j:
           d.append(m[i][j])
        
            
print("The Trace of Matrix is: ",sum(d))
print("The Normal of Matrix is: ",(sum(sq)**0.5))

The Trace of Matrix is:  15
The Normal of Matrix is:  16.881943016134134
